### ISSUE TITLE
When I do php run.php it doesn't work.

### ISSUE THREAD

**Issue by Aiddog10** [mikealmond/hq-trivia-assistant#11]
During a game, I did php run.php. I get a constant stream of 
`Connected.
Reconnecting...

Connected.
Reconnecting...

Connected.
Reconnecting...`. What am I supposed to do? I have the right ID and Bearer Token because now it says `Broadcast ended. Next show on Friday, 26-Jan-2018 15:00:00 EST for $2500.{My Username}`. So can I not have my HQ open on my phone while I am doing this?

**Comment by ifvictr** [comment]
@Aiddog10 You can run it on a separate computer. This just connects to the API with your credentials.

**Comment by robertsmith7** [comment]
The game most likely needs to be starting when you run the program, try it again at 15 est and make sure you have the correct id and bearer token.

**Comment by topper59** [comment]
I would advise against using the same account on both the phone and the bot, because it could easily be detected by HQ that you're running on two different devices with the same account. I dunno if they'll do anything with that info, but you never know. I have two separate accounts and it works great.

**Comment by mattbarker016** [comment]
Have you still been having success with the two accounts? I've ran into the same issue originally posted about.

**Comment by topper59** [comment]
Still works for me! I've had no issues, connecting with two accounts.

**Comment by Aiddog10** [comment]
@topper59 I've used a different account and it still says connected. Reconnecting. on a loop. Can you tell me what you did to set up your script? I will also try to set this script up on a mac VM (I'm running mac natively but something I installed could be interfereing

**Comment by topper59** [comment]
Hmm, nothing special just input my tokens in the file and did php run.php.

When no questions are up it does say Connected and then reconnecting periodically, and then when a question appears it pops up with the results pretty quickly.

**Comment by Aiddog10** [comment]
now that I reinstalled the git, it gives me a totally different error. here it is
`Fatal error: Uncaught Dotenv\Exception\InvalidPathException: Unable to read the environment file at /Users/Aiddog10/hq-trivia-assistant/.env. in /Users/Aiddog10/hq-trivia-assistant/vendor/vlucas/phpdotenv/src/Loader.php:75
Stack trace:
#0 /Users/Aiddog10/hq-trivia-assistant/vendor/vlucas/phpdotenv/src/Loader.php(52): Dotenv\Loader->ensureFileIsReadable()
#1 /Users/Aiddog10/hq-trivia-assistant/vendor/vlucas/phpdotenv/src/Dotenv.php(91): Dotenv\Loader->load()
#2 /Users/Aiddog10/hq-trivia-assistant/vendor/vlucas/phpdotenv/src/Dotenv.php(48): Dotenv\Dotenv->loadData()
#3 /Users/Aiddog10/hq-trivia-assistant/run.php(14): Dotenv\Dotenv->load()
#4 {main}
  thrown in /Users/Aiddog10/hq-trivia-assistant/vendor/vlucas/phpdotenv/src/Loader.php on line 75`
