### ISSUE TITLE
Different percentages under same question

### ISSUE THREAD

**Issue by pazon12** [mikealmond/hq-trivia-assistant#21]
A friend of mine are both using the bot under his credentials. He got different percentages than I do... is it an internet speed thing or is there something going on underlying the code?

**Comment by Codeseys** [comment]
How do u get the answers? I only get errors even with my credentials put in:
 --------------------------------------



Which of these is NOT a skin care brand?

--------------------------------------------------------
“NOT” DETECTED. USE THE ANSWER THAT IS THE LEAST SUCCESSFUL
--------------------------------------------------------
METHOD 1
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /home/bala/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php:189
Stack trace:
#0 /home/bala/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(167): Symfony\Component\DomCrawler\Crawler->addHtmlContent('<!doctype html>...', 'UTF-8')
#1 /home/bala/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(118): Symfony\Component\DomCrawler\Crawler->addContent('<!doctype html>...')
#2 /home/bala/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(67): Symfony\Component\DomCrawler\Crawler->add('<!doctype html>...')
#3 /home/bala/hq-trivia-assistant/functions.php(173): Symfony\Component\DomCrawler\Crawler->__construct('<!doctype html>...')
#4 /home/bala/hq-trivia-assistant/functions.php(105): handle_responses(Array, Array, 'Which of these ...')
#5 /home/bala/hq-trivia-assistant/vendor/guzzlehttp/promises/src/Promise.php(203): {closure}(Array)
#6 /home/bala/hq-trivia-assistant/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promis in /home/bala/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php on line 189

**Comment by Aiddog10** [comment]
How did you get this working? I filled in my 6 digit user ID and my 396 digit Token found under the Authentication tab. I filled in the .env file and it looks like this.
![screen shot 2018-01-28 at 9 25 22 pm](https://user-images.githubusercontent.com/18250216/35491025-f9e96070-0471-11e8-9c40-d823c96cb5eb.png)
Do I need to name my .env file something different? I tried using an ID I was currently using in-game and using one I wasn't currently using. It just kept cycling between Connected. and Reconnecting. After a while, it said something that I didn't record but it looked like HTML. What did you do to get the script to work at all? Now it says when the next game is if I do php run.php, but I removed the ID and Token from the file and it still had the schedule

**Comment by Codeseys** [comment]
litterally all i did was do what you did to the .env file. I put my ID and token in. During the game it cycles  btwn connecting and reconnecting then displays the question from the game. I dont get the answer, instead i just get an error.

**Comment by pazon12** [comment]
Hey... none of this was my question. If you want help, talk on a new issue or open one. There are plenty of people that will help, **but not here.**
Thank you.

**Comment by mikealmond** [comment]
@pazon12 It's likely that the results coming back are different based on a few factors. Google tailers it's search results to the user based on a bunch of different factors including location and device. Are you both in the same building when you're running it?

**Comment by mikealmond** [comment]
@Codeseys You need to install the PHP DOM component. See https://github.com/mikealmond/hq-trivia-assistant/issues/14#issuecomment-361279545

**Comment by mikealmond** [comment]
@Aiddog10 you need to rename the file `.env` and not `info.env`

**Comment by pazon12** [comment]
@mikealmond He's in like New York and I'm in Illinois. Should I run this bot with google logged out and it would work better? Because I'm pretty sure the speed of electricty isn't comparable to bowling balls.

**Comment by Aiddog10** [comment]
@Mikealmond what do you mean? Files (at least on Mac) have to have a name as well as an extension. I can’t name it .env. It is info.env

**Comment by mikealmond** [comment]
@pazon12 Logging out wouldn't make much a difference. The HQ script isn't using sending any cookies along with the Google requests to verify your identity. Google is just changing the search results based on you and your friends locations.

**Comment by mikealmond** [comment]
@Aiddog10, you can. Finder defaults to hiding files with names that start with a `.`. You can view them via Terminal or toggle the hidden files visibility flag https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/

**Comment by Aiddog10** [comment]
@mikealmond So would the whole file name be .env.env or just .env? When I tried to put it as .env, it says those names are reserved for system files. Also inside the .env file, should I have a space between HQ_BEARER_TOKEN and the token like this: `HQ_BEARER_TOKEN:xxxxxxxxxxx `
or like this: `HQ_BEARER_TOKEN: xxxxxxxxxxxxx `?
