### ISSUE TITLE
Error when question appear

### ISSUE THREAD

**Issue by KnottyCord** [mikealmond/hq-trivia-assistant#30]
Here is the error I get in the console
METHOD 1
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /home/knottycord/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php:189
Stack trace:
#0 /home/knottycord/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(167): Symfony\Component\DomCrawler\Crawler->addHtmlContent('<!doctype html>...', 'UTF-8')
#1 /home/knottycord/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(118): Symfony\Component\DomCrawler\Crawler->addContent('<!doctype html>...')
#2 /home/knottycord/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(67): Symfony\Component\DomCrawler\Crawler->add('<!doctype html>...')
#3 /home/knottycord/hq-trivia-assistant/functions.php(173): Symfony\Component\DomCrawler\Crawler->__construct('<!doctype html>...')
#4 /home/knottycord/hq-trivia-assistant/functions.php(105): handle_responses(Array, Array, 'In which film w...')
#5 /home/knottycord/hq-trivia-assistant/vendor/guzzlehttp/promises/src/Promise.php(203): {closure}(Array)
#6 /home/knottycord/hq-trivia-assistant/vendor/guzzlehttp/ in /home/knottycord/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php on line 189

**Comment by Codeseys** [comment]
sudo apt-get install php7.1-dom
