### ISSUE TITLE
PHP Fatal Error Issue

### ISSUE THREAD

**Issue by alistairdev** [mikealmond/hq-trivia-assistant#39]
Hi, I get this. It loads up the question but then shows this:
`Which of the following player tokens was introduced by Monopoly in 2017?
METHOD 1
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /root/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php:189
Stack trace:
#0 /root/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(167): Symfony\Component\DomCrawler\Crawler->addHtmlContent('<!doctype html>...', 'UTF-8')
#1 /root/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(118): Symfony\Component\DomCrawler\Crawler->addContent('<!doctype html>...')
#2 /root/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php(67): Symfony\Component\DomCrawler\Crawler->add('<!doctype html>...')
#3 /root/hq-trivia-assistant/functions.php(173): Symfony\Component\DomCrawler\Crawler->__construct('<!doctype html>...')
#4 /root/hq-trivia-assistant/functions.php(105): handle_responses(Array, Array, 'Which of the fo...')
#5 /root/hq-trivia-assistant/vendor/guzzlehttp/promises/src/Promise.php(203): {closure}(Array)
#6 /root/hq-trivia-assistant/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Array, Array)
 in /root/hq-trivia-assistant/vendor/symfony/dom-crawler/Crawler.php on line 189`

**Comment by ps-one** [comment]
You don't have php-xml package installed.
sudo apt-get install php-xml
OR
sudo apt-get install php7.1-dom
