### ISSUE TITLE
Run Fatal Error - Any idea?

### ISSUE THREAD

**Issue by amberphoenix** [mikealmond/hq-trivia-assistant#41]
C:\Users\Michael\Documents\GitHub\hq-trivia-assistant>php run.php

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\Users\Michael\Documents\GitHub\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
Stack trace:
#0 C:\Users\Michael\Documents\GitHub\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\Users\Michael\Documents\GitHub\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\Users\Michael\Documents\GitHub\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyH in C:\Users\Michael\Documents\GitHub\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by manofsteel2017** [comment]
same error as me LOL 
the dev has not replied yet

**Comment by manofsteel2017** [comment]
I'm not using xwamp though. 
I ran the php straight from the hi assist folder with git.

Can you tell me how to run it with xwamp?
Thanks.

**Comment by tombets2424** [comment]
if anyone is still getting the ssl certificate error try this #54

**Comment by manofsteel2017** [comment]
tried it and didn't work.
