### ISSUE TITLE
help with this error please?

### ISSUE THREAD

**Issue by shorty1987** [mikealmond/hq-trivia-assistant#45]
What college football team’s chant is also likely to be heard on a farm?
METHOD 1
PHP Notice:  Undefined offset: 1 in C:\Users\justi\Desktop\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\S
treamHandler.php on line 102
PHP Notice:  Undefined offset: 1 in C:\Users\justi\Desktop\hq-trivia-assistant\vendor\guzzlehttp\guzzle\src\Handler\S
treamHandler.php on line 103
PHP Notice:  Undefined offset: 0 in C:\Users\justi\Desktop\hq-trivia-assistant\functions.php on line 168
PHP Fatal error:  Uncaught TypeError: stripos() expects parameter 1 to be string, null given in C:\Users\justi\Deskto
p\hq-trivia-assistant\functions.php:168
Stack trace:
#0 C:\Users\justi\Desktop\hq-trivia-assistant\functions.php(168): stripos(NULL, 'yahoo.com')
#1 C:\Users\justi\Desktop\hq-trivia-assistant\functions.php(105): handle_responses(Array, Array, 'What college fo...'
)
#2 C:\Users\justi\Desktop\hq-trivia-assistant\vendor\guzzlehttp\promises\src\Promise.php(203): {closure}(Array)
#3 C:\Users\justi\Desktop\hq-trivia-assistant\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Pro
mise::callHandler(1, Array, Array)
#4 C:\Users\justi\Desktop\hq-trivia-assistant\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Pr
omise::GuzzleHttp\Promise\{closure}()
#5 C:\Users\justi\Desktop\hq-trivia-assistant\vendor\guzzlehttp\promises\src\Promise.php(246): GuzzleHttp\Promise\Tas
kQueue->run(true)
#6 C:\Users\justi\Desktop\hq-trivia-assistant\vendor\guzzlehttp\promises\src\Promise.php(223): GuzzleHttp\ in C:\User
s\justi\Desktop\hq-trivia-assistant\functions.php on line 168

it loaded the question but then this error happened

**Comment by rizzryan** [comment]
Probably update your version of php. Type php -v in Terminal/Command Prompt and tell me what version you have.

**Comment by shorty1987** [comment]
PHP 7.2.2 (cli) (built: Jan 31 2018 19:31:15) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by rizzryan** [comment]
Try this https://github.com/mikealmond/hq-trivia-assistant/issues/14#issuecomment-361279545

**Comment by shorty1987** [comment]
sudo apt-get install php7.1-dom, where can i get this?

**Comment by shorty1987** [comment]
$ sudo apt-get install php7.1-dom
bash: sudo: command not found
