### ISSUE TITLE
Error when running - Can't read environment file

### ISSUE THREAD

**Issue by JChazzer** [mikealmond/hq-trivia-assistant#50]
Hi,

When running the program, I am receiving this error:

```
C:\Users\Charlie\Desktop\hq-trivia-assistant-master>
C:\Users\Charlie\Desktop\hq-trivia-assistant-master>php run.php
PHP Fatal error:  Uncaught Dotenv\Exception\InvalidPathException: Unable to read the environment file at C:\Users\Charlie\Desktop\hq-trivia-assistant-master\.env. in C:\Users\Charlie\Desktop\hq-trivia-assistant-master\vendor\vlucas\phpdotenv\src\Loader.php:75
Stack trace:
#0 C:\Users\Charlie\Desktop\hq-trivia-assistant-master\vendor\vlucas\phpdotenv\src\Loader.php(52): Dotenv\Loader->ensureFileIsReadable()
#1 C:\Users\Charlie\Desktop\hq-trivia-assistant-master\vendor\vlucas\phpdotenv\src\Dotenv.php(91): Dotenv\Loader->load()
#2 C:\Users\Charlie\Desktop\hq-trivia-assistant-master\vendor\vlucas\phpdotenv\src\Dotenv.php(48): Dotenv\Dotenv->loadData()
#3 C:\Users\Charlie\Desktop\hq-trivia-assistant-master\run.php(14): Dotenv\Dotenv->load()
#4 {main}
  thrown in C:\Users\Charlie\Desktop\hq-trivia-assistant-master\vendor\vlucas\phpdotenv\src\Loader.php on line 75

```

Thanks for your help!

Thanks!

**Comment by JChazzer** [comment]
UPDATE:

I have manged to resolve this issue after many attempts.

I first tried to get rid of the code throwing up the problem, and after a few snippets of code deleted, I manged to run the program with no errors (well it told me when the next broadcast was, at least). However, it was showing the next game in the US - not the UK where I am. 

Next, I tried reinstalling the whole thing, and I got given the same error, however, I realised this command of code wasn't running: `cp .env.dist .env`. This probably didn't mean anything, but I changed 'cp' to 'copy' and Windows terminal copied it. I filled in the details and it worked, and is now showing me the next broadcast in the UK.
