### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by zanhaq10** [mikealmond/hq-trivia-assistant#7]
Hey I'm not the best with code and computer, so I can't seem to get this working. I have installed XAMP, and composer, and have confirmed they both work through command line. I just don't know how to run this trivia assistant on, or how I should run it. I have tried running it on a localhost web server, but I always get a ton of errors. like 
Fatal error: Uncaught Dotenv\Exception\InvalidPathException: Unable to read the environment file at C:\xampp\htdocs\HQ\.env. in C:\xampp\htdocs\HQ\vendor\vlucas\phpdotenv\src\Loader.php:75 Stack trace: #0 C:\xampp\htdocs\HQ\vendor\vlucas\phpdotenv\src\Loader.php(52): Dotenv\Loader->ensureFileIsReadable() #1 C:\xampp\htdocs\HQ\vendor\vlucas\phpdotenv\src\Dotenv.php(91): Dotenv\Loader->load() #2 C:\xampp\htdocs\HQ\vendor\vlucas\phpdotenv\src\Dotenv.php(48): Dotenv\Dotenv->loadData() #3 C:\xampp\htdocs\HQ\run.php(14): Dotenv\Dotenv->load() #4 {main} thrown in C:\xampp\htdocs\HQ\vendor\vlucas\phpdotenv\src\Loader.php on line 75

**Comment by mikealmond** [comment]
THe environment file needs to be named `.env`
