### ISSUE TITLE
php predictions.php — ServerException

### ISSUE THREAD

**Issue by pokono** [mikealmond/hq-trivia-assistant#76]
How to run `predictions.php`?

When I try to run it (`php predictions.php`) I get:

```
Zebras are native to which continent?
METHOD 1
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `GET https://www.google.ca/search?q=Zebras+are+native+to+which+continent%3F` resulted in a `503 Service Unavailable` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><meta http-equiv="content-type" content="te (truncated...)
 in /home/vagrant/hq/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/vagrant/hq/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/vagrant/hq/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/vagrant/hq/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/vagrant/hq/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{cl in /home/vagrant/hq/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```

**Comment by nolanplatt** [comment]
You don't run `predictions.php`. You run `php run.php`  Please read the tutorial before creating an issue...

**Comment by pokono** [comment]
@nolanplatt It is unrelated to what I am asking. `run.php` works fine. I'm trying to improve this package, and I was interested in running the examples. So I am asking.

**Comment by pokono** [comment]
I don't know why but the issue was caused by PIA VPN running on my mac. I would still be curious to understand what is causing the issue here, but it's not related to the code.
