### ISSUE TITLE
Android 7 Certificate Solution

### ISSUE THREAD

**Issue by Zjjc12** [mikealmond/hq-trivia-assistant#95]
For Android 7 and above, there is a newly introduced security feature. The normal certificate won't work. 
Source: https://medium.com/@elye.project/android-nougat-charlesing-ssl-network-efa0951e66de.

The app's AndroidManifest.xml file has to be changed and a network_security_config.xml file need to be added.
https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/

I personally couldn't get apktool to working by itself (you can try if you want).

An easy solution is:
1. Download https://github.com/levyitay/AddSecurityExceptionAndroid.
2. Download the newest HQ Apk https://apkpure.com/hq-trivia/com.intermedia.hq.
3. Then rename the apk to something easier to type like hq.apk and move it into the add security exception folder.
4. IMPORTANT: This will not work because of the outdated apktool. Download the newest apktool 
https://bitbucket.org/iBotPeaches/apktool/downloads/
and rename it to apktool.jar
(It had an error about decoding font for me).
5. Replace the old apktool.jar in the add security exception folder with the new one you just downloaded.
6. Open terminal or cmd and type ./addSecurityExceptions.sh myApp.apk.
7. Delete your hq app from your phone.
8. Move the new apk to your android and install it. (I used android file transfer and moved it to download folder. Then I opened it up from there).
9. Then do everything said here https://github.com/mikealmond/hq-trivia-assistant/issues/82.

This will solve the ssl certificate problem on charles for Android 7.
(only for the app you manipulated, in this case it's hq)

I'll try to answer questions about this but I'm not an expert.
And don't waste your money on paying for tutorials.

**Comment by chaoscreater** [comment]
I've created the new apk, but when I tried to install it, it says the apk package is corrupted. I don't see any errors in the command prompt when it was creating the apk. No decode errors.

**Comment by Sprinklefart** [comment]
when typing ./addSecurityExceptions.sh myApp.apk into git bash( which i'm not sure if that is the right place)  it give me this

./addSecurityExceptions.sh: line 13: keytool: command not found
Input file (myApp.apk) was not found or was not readable.
mkdir: cannot create directory ‘/tmp/myApp/res/xml’: No such file or directory
cp: cannot create regular file '/tmp/myApp/res/xml/.': No such file or directory
grep: /tmp/myApp/AndroidManifest.xml: No such file or directory
./addSecurityExceptions.sh: line 35: /tmp/myApp/AndroidManifest.xml.new: No such file or directory
mv: cannot stat '/tmp/myApp/AndroidManifest.xml.new': No such file or directory
S: WARNING: Could not write to (C:\Users\a\AppData\Local\apktool\framework), using C:\Users\a\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
W: Can't empty framework directory, no file found at: C:\Users\a\AppData\Local\Temp\1.apk
Building new APK myApp_new.apk
I: Using Apktool 2.3.1
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.io.FileNotFoundException: C:\Users\a\AppData\Local\Temp\myApp (The system cannot find the file specified)
        at brut.androlib.Androlib.readMetaFile(Androlib.java:265)
        at brut.androlib.Androlib.build(Androlib.java:277)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:75)
Caused by: brut.directory.DirectoryException: java.io.FileNotFoundException: C:\Users\a\AppData\Local\Temp\myApp (The system cannot find the file specified)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
        at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
        at brut.androlib.Androlib.readMetaFile(Androlib.java:261)
        ... 4 more
Caused by: java.io.FileNotFoundException: C:\Users\a\AppData\Local\Temp\myApp (The system cannot find the file specified)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
        ... 7 more
./addSecurityExceptions.sh: line 43: jarsigner: command not found

I'm new to this and am not sure what to do know, any help is appreciated!

**Comment by chaoscreater** [comment]
@Zjjc12 - I'm using the method you wrote. I've done exactly step by step. When it built the apk, it added _new to the filename. I copied the apk to my phone and can see the apk icon (normally you won't if it's corrupted I think). But when I install it, it just says it's corrupted. The file size of the latest HQ apk (working on my phone) is 17,938 KB and the one that I built using your method is 17,995 KB.

I did use the one you've already built, but it may not be supported in the future, so I'd like to build one myself to be future proof.

@Sprinklefart - you may need to install Python v3.6.x and Java SDK.

**Comment by Sprinklefart** [comment]
@chaoscreater ive installed both bout still get the same message, any idea?

**Comment by chaoscreater** [comment]
I'm assuming you're using Windows? Run sysdm.cpl and it should open up System Properties. Go to the Advanced Tab and choose Environmental Variables. Under the "System Variables" section, find the "Path" variable and add your Java JRE or Java SDK folder bin folder path in there. For example, mine is:

C:\Program Files (x86)\Java\jre1.8.0_144\bin

You'll want to check the exact folder path of your Java installation. I'm not using the latest Java version, so my path will be different to yours. If you have both Java JRE and Java SDK installed, just use the bin path for the Java SDK. 

Other than that, I don't know what else to suggest. I would probably just download the apk that Zjjc12 attached. I didn't get any errors building my own apk, but my apk couldn't be installed on my Galaxy S8+ running Nougat (Android 7.0). It kept saying the package is corrupted. I ended up installing the apk that Zjjc12 created, but I couldn't get Charles proxy working on my phone. I ended up grabbing my mum's iPhone 5S and then followed the rest of the tutorials posted here https://github.com/mikealmond/hq-trivia-assistant/issues/82

As long as you grab the important information you need, i.e the bearer ID / authorization key, then you'll be able to use the bot.

**Comment by Zjjc12** [comment]
I used a mac, so I used terminal. It might be different.
I think you might have to rename the HQ.apk to myApp.apk.

**Comment by chaoscreater** [comment]
I did try renaming to myApp.apk, but the built apk still doesn't work on my phone.

When I said Charles doesn't work for me, I'm talking about setting up the certificate on my phone. I'm using a Galaxy S8+, which is running Android 7. The stuff you linked is for Android 6. In the guide, it makes a reference to your post here:

For Android 7.0+ see **#95**

**On android phones with android 6 and lower:**
• Open the file from a file manager such as File Commander. You will be prompted to save the certificate.
• Give the certificate a name and Okay it as trusted (be sure to disable or remove it once you're done).
• You are required to set up a PIN once the certificate is installed. A prompt will appear asking to set up a PIN. Add the new PIN.
• Go to the Settings App > Wifi > Press and hold down the Wifi Network currently connected to. When the modal appears click Modify Network.
• Select Show Advanced Options to reveal proxying options.
• Under Proxy select Manual.
• In the Proxy Host Name box enter the enter in the IPV4 Address you got from your computer.
• In the Proxy Port Field enter the Port (8888), as you did when configuring Charles.
• Save


Anyway, I've already got this sorted. I just needed to use my mum's iPhone 5s to set up my certificate and used Charles to find my bearer ID, etc. Once you have that, you can set it up easily. I'm using 2 separate bots now.

**Comment by Sprinklefart** [comment]
Thank you guys for the help, i was able to build the apk, but it wouldn't install, im using a Oneplus 5t on android 8 if that helps.
